package:
    name: datac
    # version: x.y.z
    # The version string is stored in `datac/version.py`.
    # `build.sh` includes code to properly incorporate the version
    # string in the built package.

about:
    home: https://github.com/jrsmith3/datac
    license: MIT
    summary: Utility for managing 2D data

source:
    git_url: ..

build:
    # noarch_python: True
    string: {{ environ.get('GIT_BUILD_STR', '') }}

requirements:
    build:
        - python
        - matplotlib
        - astropy
        - pyyaml
        - pathlib
    run:
        - python
        - matplotlib
        - astropy
        - pyyaml
        - pathlib

test:
    files:
        - ../test/test_Datac.py

    requires:
        - nose
