package:
    name: datac
    # version: x.y.z
    # The version string is stored in `datac/version.py`.
    # `build.sh` includes code to properly incorporate the version
    # string in the built package.

about:
    home: https://github.com/jrsmith3/datac
    license: MIT
    summary: Utility for managing 2D data

source:
    path: ..

requirements:
    build:
        - python
    run:
        - python

test:
    files:
        - ../test/test_Datac.py

    requires:
        - nose
